# Generated by Django 3.2.8 on 2022-02-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('strand', models.CharField(max_length=100)),
                ('items', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('dateofborrow', models.DateField()),
                ('dateofreturn', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('strand', models.CharField(max_length=100)),
                ('shirt', models.IntegerField()),
                ('short', models.IntegerField()),
                ('slacks', models.IntegerField()),
                ('joggingpant', models.IntegerField()),
                ('size', models.CharField(max_length=100)),
                ('mop', models.CharField(max_length=100)),
                ('addresses', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('borrowers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('strand', models.CharField(max_length=100)),
                ('shirt', models.IntegerField()),
                ('short', models.IntegerField()),
                ('slacks', models.IntegerField()),
                ('joggingpant', models.IntegerField()),
                ('size', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
