# Generated by Django 3.2.8 on 2022-02-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='status',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrow',
            name='username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrow',
            name='dateofborrow',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='dateofreturn',
            field=models.CharField(max_length=100),
        ),
    ]
