# Generated by Django 3.2.8 on 2022-02-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220206_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='note',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
