# Generated by Django 3.2.8 on 2022-02-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_numdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numdata',
            name='noborrow',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='numdata',
            name='nobuy',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='numdata',
            name='noreserver',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
