# Generated by Django 3.2.8 on 2021-11-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211108_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnumbuy', models.CharField(max_length=100)),
                ('fullnamebuy', models.CharField(max_length=100)),
                ('emailbuy', models.CharField(max_length=100)),
                ('contactbuy', models.CharField(max_length=100)),
                ('genderbuy', models.CharField(max_length=100)),
                ('coursebuy', models.CharField(max_length=100)),
                ('strandbuy', models.CharField(max_length=100)),
                ('shirt', models.CharField(max_length=100)),
                ('short', models.CharField(max_length=100)),
                ('slacks', models.CharField(max_length=100)),
                ('joggingpant', models.CharField(max_length=100)),
            ],
        ),
    ]
