# Generated by Django 3.2.8 on 2022-02-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220203_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
