# Generated by Django 3.2.8 on 2021-11-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_buy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='contactbuy',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='coursebuy',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='emailbuy',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='fullnamebuy',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='genderbuy',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='idnumbuy',
            new_name='idnum',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='strandbuy',
            new_name='strand',
        ),
    ]
