# Generated by Django 3.2.8 on 2022-02-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_buy_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='note',
            field=models.CharField(max_length=1000),
        ),
    ]
