# Generated by Django 3.2.8 on 2021-11-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211113_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('strand', models.CharField(max_length=100)),
                ('shirt', models.CharField(max_length=100)),
                ('short', models.CharField(max_length=100)),
                ('slacks', models.CharField(max_length=100)),
                ('joggingpant', models.CharField(max_length=100)),
            ],
        ),
    ]
