# Generated by Django 3.2.8 on 2022-02-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_numdata_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('borrowers', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='NumData',
        ),
    ]
