# Generated by Django 3.2.8 on 2022-02-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_buy_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='note',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='note',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
