# Generated by Django 3.2.8 on 2022-02-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220208_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='timeofborrow',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrow',
            name='timeofreturn',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
