# Generated by Django 3.2.8 on 2021-11-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_borrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='dateofborrow',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='dateofreturn',
        ),
    ]
