# Generated by Django 3.2.8 on 2021-11-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211113_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='contact',
            new_name='contactborrow',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='course',
            new_name='courseborrow',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='email',
            new_name='emailborrow',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='fullname',
            new_name='fullnameborrow',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='idnum',
            new_name='idnumborrow',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='itemfind',
            new_name='itemfindborrow',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='items',
            new_name='itemsborrow',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='quantity',
            new_name='quantityborrow',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='strand',
            new_name='strandborrow',
        ),
    ]
