# Generated by Django 3.2.8 on 2021-11-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211116_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='itemfindborrow',
        ),
    ]
