# Generated by Django 3.2.8 on 2021-11-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_borrow_itemfindborrow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='contactborrow',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='courseborrow',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='emailborrow',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='fullnameborrow',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='idnumborrow',
            new_name='idnum',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='itemsborrow',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='quantityborrow',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='strandborrow',
            new_name='strand',
        ),
    ]
