# Generated by Django 3.2.8 on 2021-11-26 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211116_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='dateofborrow',
            field=models.DateField(default=datetime.datetime(2021, 11, 26, 14, 23, 56, 310658)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrow',
            name='dateofreturn',
            field=models.DateField(default=datetime.datetime(2021, 11, 29, 14, 24, 31, 37424)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy',
            name='size',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='course',
            field=models.CharField(default='COET', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(default='q', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='size',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrow',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='buy',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='buy',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='buy',
            name='joggingpant',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='buy',
            name='shirt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='buy',
            name='short',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='buy',
            name='slacks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='joggingpant',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='shirt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='short',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='slacks',
            field=models.IntegerField(),
        ),
    ]
